### PR TITLE
Project 7: Bootstrap project

### PR DESCRIPTION
**Pull request by ahmetbozaci**
This project has been built with Bootstrap framework. I used minimal CSS. It has been a very teaching experience.

Used Technologies:

1- HTML
2- CSS
3- Bootstrap

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet.😟 You need to work more on it. Your project is almost completed. But 2 more changes required to approve it. 
_It's okay. We are here to learn. Don't get discouraged. Work even more hard. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**


- [x] Please add an image under **newsletter** as shown below
chrome-capture (8)

- [x] Please align the @2020 as shown below 
chrome-capture (9)

**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Comment by ahmetbozaci** [comment]
- I added the image on the newsletter, but I forget "/" in folder path. I fixed it.
- At the footer "newsweek logo"  and date aligned with flex

**Review by arslanbisharat — APPROVED** [review]
### Congratulations APPROVED :clap:
Hello I can see you worked really hard on this project. and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
_The clone shows a good understanding and usage of Bootstrap 💯_

- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

**Comment by arslanbisharat** [comment]
> * I added the image on the newsletter, but I forget "/" in the folder path. I fixed it.
> * At the footer "Newsweek logo"  and date aligned with flex

Thank you for these changes. I approved the project.

**Pull request merged**
